### ISSUE TITLE
Adapt the script for Mac OS X

### ISSUE THREAD

**Issue by AntoineTurmel** [AntoineTurmel/nightingale-tools#16]
I assume it should work out of the box, there might need some tweaking to upload .dmg instead of .tar.gz

Also cron or equivalent would need to be configure to build each day.

@ilikenwf can you test it ?

**Comment by ilikenwf** [comment]
Eventually...ping me after this next release and I'll get it working.

**Comment by ilikenwf** [comment]
You can close this one now, once you merge my pull request.

**Comment by AntoineTurmel** [comment]
@ilikenwf is this on your Mac OS X crontab or anything like this ?

**Comment by ilikenwf** [comment]
Yes...on cron. Also glad it works. w00t!

**Comment by AntoineTurmel** [comment]
@ilikenwf so there is a cron on Mac OS X, good to know. I still have to reinstall all tools on Windows and to try the script but I suppose it will work...

**Comment by ilikenwf** [comment]
Good!
