### ISSUE TITLE
Chain a .sh script on bash for Windows

### ISSUE THREAD

**Issue by AntoineTurmel** [AntoineTurmel/nightingale-tools#21]
On start-msvc9.bat, I'm chaining the buildbot script right after bash with:

```
"%MOZILLABUILD%\msys\bin\bash" /c/nightingale-tools/buildbot/buildbot_ng.sh --login -i
```

The thing is, I do not get all PATHs defined... I have more PATHs if I manually do:

```
"%MOZILLABUILD%\msys\bin\bash" --login -i
```

and then

``` bash
echo $PATH
```

Should I defined myself missing PATHs in "set PATH" or I am missing something ?
@rsjtdrjgfuzkfg ?

**Comment by AntoineTurmel** [comment]
Ok padenot from Mozilla helped me on that one, I should put my script after --login -i and it should work.

**Comment by rsjtdrjgfuzkfg** [comment]
I put my stuff before the line `"%MOZILLABUILD%\msys\bin\bash" --login -i` and it worked... you ment to close here or are there open questions?

**Comment by AntoineTurmel** [comment]
Resolved for me :) Thanks anyway @rsjtdrjgfuzkfg
