### ISSUE TITLE
Put the Mac Mini in production for producing nightlies

### ISSUE THREAD

**Issue by AntoineTurmel** [AntoineTurmel/nightingale-tools#32]
Currently, @ilikenwf Mac Mini is sometimes producing builds.
I also have a Mac Mini and should setup it to builds our nightlies.

**Comment by ilikenwf** [comment]
The Mac cron and scheduler currently are unable to run the build scripts on
their own - I have tried as root, have included the path and .bashrc and no
good.

**Comment by AntoineTurmel** [comment]
Weird, and you can't set an app to chain the script ?

**Comment by ilikenwf** [comment]
Not so far. I even tried using the native mac scheduler, that isn't cron, and it still won't fire grr.. Note it has to be OSX 10.5 to build for now. Everything else is too new...lol

**Comment by AntoineTurmel** [comment]
wait wait wait, I thought it was working on OSX 10.6/10.7 !
http://wiki.getnightingale.com/doku.php?id=build:mac
You wrote that.

**Comment by ilikenwf** [comment]
Xulrunner at least and some other deps won't build on 10.6 or 10.7. The
nightingale client itself should but everything else is so old that it
doesn't work that way. Furthermore, we need to use the 10.5 or 10.6 sdk
anyway to support more users.

**Comment by AntoineTurmel** [comment]
ignore lasts messages, I fixed them :)

**Comment by ilikenwf** [comment]
You got it all working? How about the scheduling on cron?

**Comment by AntoineTurmel** [comment]
Ok, I think I got it to work :) Next time we have a commit, it _should_ build a nightly.

**Comment by ilikenwf** [comment]
:+1:
